Send files to file-api
TMDAD-Chat/message-receiver-api pull request #4
Opened 2022-04-15 19:54 UTC by FreddyMartinez

Circuit breaker was implemented

2022-04-17 07:45 UTC, lAngelP requested changes

2022-04-17 07:45 UTC, lAngelP commented on src/main/java/es/unizar/tmdad/service/impl/FileServiceImpl.java
> +                .baseUrl("http://localhost:8080")
Esta URI mejor si viene a través de un application.yml y se carga mediante un @Value()

2022-04-17 15:43 UTC, FreddyMartinez commented on src/main/java/es/unizar/tmdad/service/impl/FileServiceImpl.java
> +                .baseUrl("http://localhost:8080")
hecho :+1:

2022-04-18 09:09 UTC, lAngelP approved these changes

2022-04-20 14:25 UTC, merged